name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: list before folders
      shell: bash
      run: |
        pwd
        ls
        
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: list after folders
      shell: bash
      run: |
        pwd
        ls
